# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package 

#Everey time an event happens something will happen. In this case everytime that one pushes or pulls from
#main branch, something will happen.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#One or more jobs, these are a sequence of tasks
#Steps can run commands, setup tasks or run an action
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            -   name: Build and push docker image
                uses: docker/build-push-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    dockerfile: Dockerfile
                    #repository: my/repository
                    tag_with_ref: true