name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
    uses: actions/checkout@v2

      - name: Build image
        run: docker build --file ./api/Service/Dockerfile --tag my-image-name:$(date +%s)


      - name: Push frontend image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: myDocker/repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: Dockerfile.ci