name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    #DockerHub integration
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} #in gitHub repo, got to Settings/Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: antoniomm8506/githubactions_practice
        dockerfile: antoniomm8506/Dockerfile
        tags: latest
