name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
    uses: actions/checkout@v2

    - name: Push frontend image
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: antoniomm8506/gha
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        dockerfile: Dockerfile
        